<a href="https://colab.research.google.com/github/harsh194/machine_learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,11,11)

array([ 0. ,  1.1,  2.2,  3.3,  4.4,  5.5,  6.6,  7.7,  8.8,  9.9, 11. ])

In [ ]:
np.random.randint(0,10,(3,3))

array([[0, 8, 6],
       [1, 4, 7],
       [5, 4, 1]])

In [ ]:
np.random.seed(101)
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [ ]:
arr.max()

95

In [ ]:
arr.min()

9

In [ ]:
arr.mean()

60.8

In [ ]:
arr.argmax()

0

In [ ]:
arr.argmin()

7

In [ ]:
arr.arg